name: CI
on:
  push:
    branches: [main]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@master

      - name: 安装 Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.18.3

      - name: 安装依赖
        run: npm install

      - name: 打包
        run: npm run docs:build

      - name: 发布
        uses: easingthemes/ssh-deploy@v2.1.1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          ARGS: '-avzr --delete'
          SOURCE: 'docs/.vitepress/dist/'
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: 'root'
          TARGET: '/www/wwwroot/lznote'
