name: CI
on:
  push:
    branches: [main]

jobs:
  build-deploy:
    name: docs
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: build&deploy
        uses: JamesIves/github-pages-deploy-action@v4.2.3
        env:
          ACCESS_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build
          BUILD_SCRIPT: npm install && npm run build
